---
- name: Install Apache and Upload Web Page
  hosts: linux
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html


  tasks:
  - name: Install Web Server
    apt: name=apache2 state=present

  - name: Copy WebPage To Server
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start And Enable Server
    service: name=apache2 state=started enabled=yes


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
