

- hosts: cat
  strategy: free
    
  
  tasks:

  - name: Config ACL
    ios_config: 
      before: 
              - no ip access-list extended TELNET
      parents:
              - ip access-list extended TELNET 
      commands: 
              - permit tcp host 172.31.34.8 any eq telnet
              - permit tcp host 10.1.0.75 any eq telnet
              - permit tcp host 10.1.0.78 any eq telnet  
              - permit tcp host 10.1.0.83 any eq telnet
              - permit tcp host 10.1.0.84 any eq telnet
      match: none

  handlers:

  - name: Access-class IN
    ios_config:
      parents:
              - line vty 5
      commands: 
              - access-class TELNET in



