- name: Run BACKUP to TFTP (Switches)
  hosts: cat
  strategy: free
  vars:
    backup_root: backup
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: aandreev
    ansible_password: F26ast2013!
    
  tasks:

  - name: make "file prompt quiet"
    ios_config: 
      commands: file prompt quiet
      defaults: no
    when: use_tftp_server == true

  - name: copy run to tftp
    ios_command:
      commands:
        - copy run tftp://10.1.0.84/switches/
    when: use_tftp_server == true

- name: Run BACKUP to TFTP (ASA)
  hosts: asa
  vars:
    backup_root: backup
    ansible_network_os: asa
    ansible_connection: network_cli
    ansible_user: aandreev
    ansible_password: F26ast2013!

  tasks:

  - name: backup to tftp
    asa_command:
      commands:
        - backup /noconfirm location  tftp://10.1.0.84/
    when: use_tftp_server == true
