

- hosts: cat
  vars:
    backup_root: backup
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: ansible
    ansible_password: Super#1964AN*
    
  
  tasks:

  - name: Config vty 0 4
    ios_config: 
      before: 
              - login block-for 60 attempts 3 within 30
      parents:
              - line vty 0 4
      commands: 
              - exec-timeout 5 0
              - logging synchronous
              - timeout login response 30
      match: none

  - name: Config vty 5
    ios_config:
      parents:
              - line vty 5
      commands:  
              - exec-timeout 2 0  
              - logging synchronous
              - timeout login response 30
      match: none 
